# Generated by Django 2.0.7 on 2019-11-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_datadetailmodel_datamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadetailmodel',
            old_name='created_at',
            new_name='deployment_date',
        ),
    ]
