# Generated by Django 2.0.7 on 2019-11-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20191101_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadetailmodel',
            name='deployment_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datadetailmodel',
            name='speed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
